#!/usr/bin/env bash
# scout meta-layer registration — single source of truth for the SearXNG MCP
# registration mechanics (pin, no-cloud env var, remove-then-add, verify).
#
# Used two ways:
#   1. Standalone (technical user):   bash register-searxng.sh
#   2. Invoked by /scout:setup, which offers SearXNG registration alongside
#      browser-use.
#
# No secret is written by this script. SearXNG is self-hosted (started by
# `scout meta` as a local Docker container), so the MCP needs no API key — the
# only env var is SEARXNG_URL pointing at the local container. The container's
# own secret_key is generated by the launcher into the installed settings.yml,
# never here and never in the repo.
#
# SearXNG is opt-in: it is scout's discovery backend (finding URLs). It does NOT
# fetch content — WebFetch and the depth layer remain the fetch path. With no
# SearXNG registered, scout runs breadth-only with WebSearch.

set -u
set -o pipefail

PIN="mcp-searxng@1.5.0"
SEARXNG_URL="http://localhost:8911"

echo "== prerequisites =="
missing=0
if command -v claude >/dev/null 2>&1; then echo "claude: ok"; else echo "claude: MISSING -> https://docs.claude.com/en/docs/claude-code"; missing=1; fi
if command -v npx >/dev/null 2>&1; then echo "npx: ok"; else echo "npx: MISSING -> install Node.js (ships npx): https://nodejs.org"; missing=1; fi
if [ "$missing" -ne 0 ]; then echo "Stopping: install the missing prerequisite, then re-run."; exit 1; fi

echo
echo "== register searxng (user scope) =="
# add/add-json refuse to overwrite an existing server, so remove first (scoped to
# user so a project/local server you set up by hand is left untouched). The
# `|| true` keeps a first run (nothing to remove) from erroring under set -o
# pipefail.
claude mcp remove searxng -s user >/dev/null 2>&1 || true

# Register under the EXACT name `searxng` (coupled to the mcp__searxng__* tool
# prefix in scout's allow-list). No API key — self-hosted; SEARXNG_URL only.
claude mcp add searxng npx -s user -e SEARXNG_URL="$SEARXNG_URL" -- -y "$PIN"

echo
echo "== verify =="
claude mcp get searxng 2>&1

echo
echo "== scope-conflict check =="
# scout registers searxng at USER scope (npx mcp-searxng + SEARXNG_URL). A stray
# searxng registration at project or local scope from an UNRELATED project wins
# over scout's user-scope one (project > local > user), so the MCP fails to
# connect ("defined in multiple scopes with different endpoints" / "Connection
# closed"). Detect that and warn — never auto-remove, the other entry may belong
# to a project the user still wants.
conflict=0

# Signal 1: `claude mcp list` surfaces the multi-scope conflict on a searxng line.
list_out="$(claude mcp list 2>&1 || true)"
if printf '%s\n' "$list_out" | grep -i 'searxng' | grep -qi 'multiple scopes\|different endpoint'; then
  conflict=1
fi

# Signal 2: the RESOLVED searxng server is not scout's. scout's resolved command
# is `npx ... mcp-searxng` carrying SEARXNG_URL. If the active resolution is
# something else (e.g. a `python3 .../server.py`), a higher-priority scope is
# overriding scout's user-scope registration.
get_out="$(claude mcp get searxng 2>&1 || true)"
if printf '%s\n' "$get_out" | grep -qi 'mcp-searxng'; then
  : # resolved command is scout's npx mcp-searxng — expected
else
  conflict=1
fi

if [ "$conflict" -ne 0 ]; then
  echo "WARNING: another 'searxng' registration is shadowing scout's."
  echo "  scout registered: user scope, command 'npx -y $PIN', SEARXNG_URL=$SEARXNG_URL."
  echo "  Another 'searxng' at a different scope or endpoint is overriding it"
  echo "  (project and local scope both win over user scope), so the SearXNG MCP"
  echo "  will fail to connect until the conflict is cleared."
  echo
  echo "  Fix: remove the NON-scout entry, keeping scout's user-scope one. Try:"
  echo "    claude mcp remove searxng -s project"
  echo "  (or '-s local' if the stray entry is at local scope). Do NOT remove the"
  echo "  user-scope entry — that is scout's. Then re-run this script if needed."
else
  echo "no scope conflict detected"
fi

echo
echo "Done. If the entry shows Type: stdio, Command: npx, the pinned mcp-searxng arg, and SEARXNG_URL, the meta discovery backend is registered. Start scout with: scout meta"
