#!/usr/bin/env bash
# scout meta-layer registration — single source of truth for the SearXNG MCP
# registration mechanics (pin, no-cloud env var, remove-then-add, verify).
#
# Used two ways:
#   1. Standalone (technical user):   bash register-searxng.sh
#   2. Invoked by /scout:setup, which offers SearXNG registration alongside
#      browser-use.
#
# No secret is written by this script. SearXNG is self-hosted (started by
# `scout meta` as a local Docker container), so the MCP needs no API key — the
# only env var is SEARXNG_URL pointing at the local container. The container's
# own secret_key is generated by the launcher into the installed settings.yml,
# never here and never in the repo.
#
# SearXNG is opt-in: it is scout's discovery backend (finding URLs). It does NOT
# fetch content — WebFetch and the depth layer remain the fetch path. With no
# SearXNG registered, scout runs breadth-only with WebSearch.

set -u
set -o pipefail

PIN="mcp-searxng@1.5.0"
SEARXNG_URL="http://localhost:8911"

echo "== prerequisites =="
missing=0
if command -v claude >/dev/null 2>&1; then echo "claude: ok"; else echo "claude: MISSING -> https://docs.claude.com/en/docs/claude-code"; missing=1; fi
if command -v npx >/dev/null 2>&1; then echo "npx: ok"; else echo "npx: MISSING -> install Node.js (ships npx): https://nodejs.org"; missing=1; fi
if [ "$missing" -ne 0 ]; then echo "Stopping: install the missing prerequisite, then re-run."; exit 1; fi

echo
echo "== register searxng (user scope) =="
# add/add-json refuse to overwrite an existing server, so remove first (scoped to
# user so a project/local server you set up by hand is left untouched). The
# `|| true` keeps a first run (nothing to remove) from erroring under set -o
# pipefail.
claude mcp remove searxng -s user >/dev/null 2>&1 || true

# Register under the EXACT name `searxng` (coupled to the mcp__searxng__* tool
# prefix in scout's allow-list). No API key — self-hosted; SEARXNG_URL only.
claude mcp add searxng npx -s user -e SEARXNG_URL="$SEARXNG_URL" -- -y "$PIN"

echo
echo "== verify =="
claude mcp get searxng 2>&1
echo
echo "Done. If the entry shows Type: stdio, Command: npx, the pinned mcp-searxng arg, and SEARXNG_URL, the meta discovery backend is registered. Start scout with: scout meta"
